### PR TITLE
Linking in task execution schema

### PR DESCRIPTION
**Pull request by kellrott**

### CODE REVIEW

**Comment by kellrott** [comment]
This is a draft proposal for the workflow execution schema that uses protobuf and extends on the task execution schema.

**Comment by geoffjentry** [comment]
@kellrott Do you think it'd be worth discussing this on a call or not really?

**Comment by kellrott** [comment]
Probably only after @tetron has looked at it

**Comment by tetron** [comment]
I started playing with this in the protobuf-pa branch.

**Comment by tetron** [comment]
Take a look at PR #8

**Pull request merged**
